apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: hello-spring
          image: marcel1315/hello-spring:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: hello-spring-properties
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"