apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
spec:
  template:
    spec:
      containers:
        - name: hello-spring
          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "250Mi"
              cpu: "250m"