apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MYSQL_USER: bXktdXNlcg== # Base64 encoded value for 'my-user'
  MYSQL_PASSWORD: bXktcGFzc3dvcmQ= # Base64 encoded value for 'my-password'
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA== # Base64 encoded value for 'root-password'
