apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: hello-spring
spec:
  clusterIP: None # Makes the service headless
  selector:
    part-of: k8s-hello
    component: hello-db
  ports:
    - port: 3306
      targetPort: 3306
